language: python
python:
  - "2.6"
  - "2.7"
# bmap-tools don't support 3.x yet, thus disable.
# pypy 2.x currently also disabled, until testing fixed.
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "nightly" # currently points to 3.6-dev
#  - "pypy"
#  - "pypy3"
# command to install dependencies
install:
  - pip install codecov
  - pip install .
# command to run tests
script: python setup.py nosetests --with-coverage --cover-xml
after_success:
  - codecov
# Don't bug people yet
notifications:
  email: false

# Perform testing also using optional compressors
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pbzip2 pigz lzop liblz4-tool
# addons:
#   apt:
#     packages:
#     - pbzip2
#     - pigz
#     - lzop
#     - liblz4-tool
